services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  backend:
    build: ./backend
    ports:
      - "4001:4001"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: