name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:    
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: Backend/package-lock.json

    # Backend
    - name: Install dependencies for the backend
      working-directory: ./Backend
      run: npm i
    
    - name: Build backend
      working-directory: ./Backend
      run: npm run build --if-present
    
    - name: Run backend
      working-directory: ./Backend
      run: npm test
    # Frontend
    - name: Install dependencies for frontend
      working-directory: ./Frontend
      run: npm i

    - name: Build frontend
      working-directory: ./Frontend
      run: npm run build --if-present

    - name: Run frontend
      working-directory: ./Frontend
      run: npm text
